### ISSUE TITLE
Unable to build the MQTT Plugin

### ISSUE THREAD

**Issue by flyvert** [telldus/tellstick-server-plugins#13]
I successfully pulled and built the MQTT Plugin in early 2019. Now two years later the _same_ build server fail to build the plugin (not the original v1.0, nor the updated v1.1).

Apart from using the original build machine I have tried with a "fresh" Debian Buster, a reinstall of Debian Stretch (both running on Raspberry PI) and also a new Ubuntu 20.04 server in VMware Workstation 16 (Microsoft Windows 10).

The **tellstick.sh build-plugin** command fails when using the embedded **pip** version to collect dependencies.

```
./tellstick.sh build-plugin /home/pi/src/tellstick-server-plugins/mqtt-client
Building plugin /home/pi/src/tellstick-server-plugins/mqtt-client
Traceback (most recent call last):
File "setup.py", line 22, in <module>
extras_require=dict(cREQ='Base>=0.1\nTelldus>=0.1'),
File "/home/pi/src/tellstick-server/build/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/pi/src/tellstick-server/sdk/sdk/plugin.py", line 95, in run
requirements = self.__downloadRequirements(prebuiltPackages)
File "/home/pi/src/tellstick-server/sdk/sdk/plugin.py", line 171, in __downloadRequirements
cmd = DownloadCommand()
File "/home/pi/src/tellstick-server/build/env/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 195, in __init__
super(RequirementCommand, self).__init__(*args, **kw)
TypeError: __init__() takes at least 3 arguments (1 given)
running telldus_plugin
Could not build plugin
```
Replacing the embedded _build/env/local/lib/python2.7/site-packages/pip_ with a standard version has taken me a few steps further (I get the .egg files, but no PGP hashes, nor final .zip file).

**Comment by atchoo78** [comment]
@flyvert 
From the Tellstick server root, run:

```python

./tellstick.sh shell
source build/env/bin/activate
./tellstick.sh build-plugin /home/pi/src/tellstick-server-plugins/mqtt-client
```

I was stuck on the same thing for a while. Hope it works for you too 🙂
